blog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import singleblog.views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'blogs.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', singleblog.views.index, name='index'),
   
    url(r'^archive/', singleblog.views.archive, name="archive"), 
    url(r'^article/(?P<id>(\d+))$', singleblog.views.view_blog, name='blog_article'),
    url(r'^author/(?P<id>(\d+))$', singleblog.views.view_author, name='blog_author'),
    url(r'^author/(?P<url>(\S+))$', singleblog.views.view_url, name='author_url'), 
    url(r'^category/(?P<cid>(\d+))$', singleblog.views.category, name='category'),
    url(r'^tag/(?P<tid>(\d+))$', singleblog.views.tag, name='tag'),
    
    #user register and login
    url(r'^login/$', singleblog.views.login, name='login'),
    url(r'^register/$', singleblog.views.register, name='register'),
    url(r'^logout/$', singleblog.views.logout, name='logout'),

    #
    url(r'^search/', singleblog.views.search, name='search'),
    
    #
    url(r'user/blog/add/$', singleblog.views.add_blog, name='add_blog'),
    url(r'^user/blog/edit/(?P<id>(\d+))/$', singleblog.views.edit_blog, name='edit_blog'),
    url(r'^user/blog/remove/(?P<id>(\d+))/$', singleblog.views.remove_blog, name='remove_blog'),

    #
    url(r'user/comment/add/(?P<id>(\d+))/$', singleblog.views.add_comment, name='add_comment'),
    #url(r'user/comment/reply/(?P<id>(\d+))/$', singleblog.views.reply_comment, name='reply_comment'),
    url(r'user/comment/remove/(?P<id>(\d+))/$', singleblog.views.remove_comment, name='remove_comment'),
    url(r'user/comment/read/(?P<id>(\d+))/$', singleblog.views.read_comment, name="read_comment"),

    url(r'^user/letter/send/$', singleblog.views.send_letter, name="send_letter"),
    url(r'^user/letter/read/(?P<id>(\d+))/$', singleblog.views.read_letter, name="read_letter"),
    url(r'^user/message/view/', singleblog.views.view_history_message, name="view_history"),
    url(r'^user/message/delete/', singleblog.views.delete_messages, name="delete_messages"),

    #some ajax url for ajax
    url(r'^user/password/reset/', singleblog.views.reset_password, name="reset_password"),
    url(r'^user/password/forget/$', singleblog.views.forget_password, name="forget_password"),
    url(r'^user/avatar/reset/$', singleblog.views.set_avatar, name="set_avatar"),
    url(r'^ajax_set_author_info/$', singleblog.views.ajax_set_author_info, name='ajax_set_author_info'),
    url(r'^user/category/edit/$', singleblog.views.edit_category, name='edit_category'),
    url(r'^user/tag/edit/$', singleblog.views.edit_tag, name='edit_tag'),
	
    url(r'^getverifycode/', singleblog.views.get_verifycode, name='get_verifycode'),
    url(r'^upload/images/$', singleblog.views.upload_images, name='upload_images'),
    url(r'^about/$', singleblog.views.about, name="about"),
    url(r'^contact/$', singleblog.views.contact, name="contact"),
    url(r'^leave_message/$', singleblog.views.leave_message, name="leave_message"),
)




    

        


singleblog/models.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404
from django.db import models

class Author(models.Model):
    user_name = models.CharField(max_length=100, unique=True,  verbose_name=u'用户名')
    email = models.EmailField(unique=True, verbose_name=u'邮箱')
    password = models.CharField(max_length=200, verbose_name=u'密码')
    url = models.CharField(max_length=50, unique=True, default='', verbose_name=u'个性域名')
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name=u'加入时间')
    level = models.IntegerField(default=1, verbose_name=u'等级')
    visitors = models.IntegerField(default=0,  verbose_name=u'主页访问量')
    description = models.TextField(default="", verbose_name=u'作者简介')
    is_active = models.BooleanField(default=True, verbose_name=u'是否禁用')
    avatartype = models.SmallIntegerField(default=1, verbose_name=u'头像类型')

    def __unicode__(self):
        return self.user_name

    def get_avatar_url(self):
	url = "/static/images/user_avatar_%d_large.png" % self.avatartype
	return url

    class Meta:
        ordering = ['id']
        verbose_name_plural = verbose_name = u'作者'


class Category(models.Model):
    category_name = models.CharField(max_length=100, verbose_name=u'分类')
    author = models.ForeignKey(Author, verbose_name=u'作者')

    def __unicode__(self):
        return self.category_name

    class Meta:
	ordering = ['id']
	verbose_name_plural = verbose_name = u'分类'

class Tag(models.Model):
    tag_name = models.CharField(max_length=100, verbose_name=u'标签')
    author = models.ForeignKey(Author, verbose_name=u'作者')

    def __unicode__(self):
        return self.tag_name
   
    class Meta:
	ordering = ['id']
	verbose_name_plural = verbose_name = u'标签'


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name= u'标题')
    content = models.TextField(verbose_name=u'内容')
    count = models.IntegerField(default=0, verbose_name=u'阅读次数')
    published_date = models.DateTimeField(auto_now_add=True, verbose_name=u'发表时间')
    updated_date = models.DateTimeField(verbose_name=u'修改时间')
    author = models.ForeignKey(Author, verbose_name=u'作者')
    #is_delete = models.BooleanField(default=False, verbose_name=u'是否删除')
    visible = models.BooleanField(default=True, verbose_name=u'公开可见')
    markdown = models.BooleanField(default=False, verbose_name=u'是否使用Markdown')
    category = models.ForeignKey(Category, verbose_name=u'分类')
    tag = models.ManyToManyField(Tag, verbose_name=u'标签')

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-published_date']
        verbose_name_plural = verbose_name = u'博客'


class Comment(models.Model):
    content = models.CharField(max_length=280, verbose_name=u'内容')
    add_time = models.DateTimeField(auto_now=True, verbose_name=u'评论时间')
    sender = models.ForeignKey(Author, verbose_name=u'发送者')
    receiver_id = models.IntegerField(verbose_name=u'接收者')
    has_been_read = models.BooleanField(default=False, verbose_name=u'是否已读') 
    blog = models.ForeignKey(Blog, verbose_name=u'博客')
    #is_delete = models.BooleanField(default=False, verbose_name=u'是否删除')


    def __unicode__(self):
        return self.content

    class Meta:
        ordering = ['id']
        verbose_name_plural = verbose_name = u'评论'

class Message(models.Model):
	content = models.CharField(max_length=280, verbose_name=u'内容')
	sended_time = models.DateTimeField(auto_now=True, verbose_name=u'发送时间')
	sender_id = models.IntegerField(verbose_name=u'发送者')
	receiver_id = models.IntegerField(verbose_name=u'接收者')
	has_been_read = models.BooleanField(default=False, verbose_name=u'是否已读')
	receiver_delete = models.BooleanField(default=False, verbose_name=u'收信者删除')
	sender_delete = models.BooleanField(default=False, verbose_name=u'发信者删除')
	
	def __unicode__(self):
		return self.content
	
	def get_sender_name(self):
		sender = get_object_or_404(Author, pk=self.sender_id)
		return sender.user_name
	
	class Meta:
		ordering = ['-id']









 

    

templates/about.html
{% extends "base.html" %}
{% block title %}关于微克{% endblock %}
{% block content %}
<div class="main">
<p class="text-center"><span class="lead">微克</span>，微克是一个非常普通的CMS博客平台。除了必须有的评论系统之外，微克还支持站内私信。</p><br/>
<p class="text-center"><strong>我的文章</strong></span>
<img src="/static/images/articles.png" alt="我的文章" class="img-thumbnail">
</p>
<p class="text-center"><strong>资料管理</strong>
<img src="/static/images/info.png" alt="我的资料" class="img-thumbnail">
</p>
<p class="text-center"><strong>消息模块</strong>
<img src="/static/images/message.png" alt="我的消息" class="img-thumbnail">
</p>
<p class="text-center"><strong>分类、标签管理</strong>
<img src="/static/images/category.png" alt="分类管理" class="img-thumbnail">
</p>
</div>
{% endblock %}

templates/author_page.html
{% extends "base.html" %}
{% block title %} {{ author.user_name }}{% endblock %}

{% block aside %}
<div class="sidebar">
<p><strong type="font-size: 18px">微客信息</strong></p>
<p class="text-center">
<img src="{{ author.get_avatar_url }}" class="img-circle" width="60%" title="{{ author.user_name }}"/>
</p>
<p class="lead text-center">{{ author.user_name }}</p>
{% if not login_author or login_author.id == author.id %}<fieldset disabled>{% endif %}
<button type="button" class="btn btn-success btn-lg col-sm-12" data-toggle="modal" data-target="#letterModal"><span class="glyphicon glyphicon-envelope"></span>&nbsp;&nbsp;私信</button><br/>
<div class="modal fade" id="letterModal" tabindex="-1" role="dialog" aria-labelledby="letterModelLabel" aria-hidden="true">
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">发私信给{{ author.user_name }}</div>
		<div class="modal-body">
		<form class="form-horizontal" action="{% url send_letter %}" method="post" id="letter-form">{% csrf_token %}
		<input type="hidden" name="uid" value="{{ author.id }}"/>
		<div class="form-group required">
		<div class="col-sm-12">	
			<textarea rows="10" class="form-control textarea" name="content"  id="id_content"></textarea>
		</div>
		</div>
		<div class="modal-footer">
		<div class="form-group">
		<div class="col-sm-offset-8">
		<input type="submit" class="btn btn-success" value="发送"/>
		<input type="button" class="btn btn-default" value="取消" data-dismiss="modal"/>
		</div>
		</div>
		</div>
		</form>
		</div>
	</div>
</div>
</div>
{% if not login_author %}<fieldset disabled>{% endif %}
<p>简介:&nbsp; &nbsp;{{ author.description }}</p>
</div>
<div class="sidebar">
<p><strong type="font-size: 18px">标签</strong></p>
<p>
{% for tag in tags %}
{% autoescape off %}
{{  tag }}
{% endautoescape %}
{% endfor %}
</p>
</div>
{% endblock %}


{% block content %}
{% for blog in blogs %}
	<div class="main">
	{% if blog.visible or author.id == login_author.id %}
		<div class="page-header">
		<h3><a href="{% url blog_article blog.id %}">{{ blog.title }}</a></h3>
		<h6>
		<span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;<a href="{% url blog_author blog.author.id %}">{{ blog.author.user_name}}</a>&nbsp;&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-folder-open"> {{ blog.category.category_name }}</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-calendar"></span>&nbsp;&nbsp;{{ blog.published_date|date:"Y年m月d日" }}&nbsp;&nbsp;&nbsp;&nbsp;阅读:&nbsp;{{ blog.count }}
		</h6>
		{% autoescape off %}
		{{ blog.content|safe|truncatewords:"10" }}
		{% endautoescape %}
		</div>
	{% if login_author and author.id == login_author.id %}
		<a href="{% url edit_blog blog.id %}" class="btn btn-warning">编辑</a>
		<a href="{% url remove_blog blog.id %}" class="btn btn-danger">删除</a>
	{% else %}
		<h5><a href="{% url blog_article blog.id %}">阅读全文>></a></h5>
	{% endif %}
{% endif %}
</div>
{% endfor %}
<center>
{% if paginator.num_pages != 1 %}
<div class="main">
<ul class="pagination">
<li><a href="{% if blogs.has_previous %} ?page={{ blogs.previous_page_number }}{% endif %}">&laquo;</a></li>
{% for page_num in paginator.page_range %}
	<li {% ifequal page_num blogs.number %} class="active" {% endifequal%}><a href="?page={{ page_num }}">{{ page_num }} {% ifequal page_num blogs.number %} <span class="sr-only">(current)</span>{% endifequal %}</a><li>
{% endfor %}
<li><a href="{% if blogs.has_next %}?page={{ blogs.next_page_number }}{% endif %}">&raquo;</a></li>
</ul>
</div>
{% endif %}
</center>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
$(function(){
	$('#letter-form').submit(function(){
		$.ajax({
			url: '{% url send_letter %}',
			type: 'POST',
			data: $(this).serialize(),
			success: function(data){
				$('#id_content').val('');
				$('#letterModal').modal("hide");
				if(data.status == 'success') alert('发送成功！');
				}
			});
		return false;
	});
			
});
</script>
{% endblock %}

 

templates/blog_page.html
{% extends "base.html" %}

{% block title %}{{ blog.title }}{% endblock %}
{% block aside %}
<div class="sidebar">
{% if login_author.id == author.id %}
<p><strong type="font-size: 18px">我的资料</strong></p>
{% else %}
<p><strong type="font-size: 18px">关于作者</strong></p>
{% endif %}
<p class="text-center"><img src="{{ author.get_avatar_url }}"  class="img-circle" width="60%" title="{{ author.user_name }} "/>
</p>
<p class="lead text-center">{{ author.user_name }}</p>
<p>简介:&nbsp;{{ author.description }}</p>
</div>
{% endblock %}
{% block content %}
<div class="main">
<h3 class="text-center">{{ blog.title }}</h3>
<br/>
<h5>
	<span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;<a href="{% url blog_author blog.author.id %}">{{ blog.author.user_name }}</a>&nbsp;&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-calendar"></span>&nbsp;&nbsp;{{ blog.published_date|date:"Y年m月d日"}}&nbsp;&nbsp;&nbsp;&nbsp;阅读:&nbsp;&nbsp;{{ blog.count }}
</h5>
<h6>
{% for tag in blog.tag.all %}
<span class="label label-info">{{ tag.tag_name}}</span>
{% endfor %}
</h6>
<p>
{% autoescape off %}
{{ blog.content}}
{% endautoescape %}
</p>
{% if login_author and login_author.id == author.id %}
<h5>
<a href="{% url edit_blog blog.id %}">编辑</a>><a href="{% url remove_blog blog.id %}">删除</a>
</h5>
{% endif %}
<br/><br/>
<blockquote>评论&nbsp;&nbsp;(共<span id="comment_count">{{ comments|length }}</span>条)</blockquote>
<hr/>
<div id="comment-area">
{% for comment in comments %}
<div id="comment_{{ comment.id }}">
	<div class="col-sm-2">
		<img src="{{ comment.sender.get_avatar_url }}" class="img-circle" width="50%" title="{{ comment.sender.user_name }}">
	</div>
				<div class="col-sm-10">
	                 <h6><a href="{% url blog_author comment.sender.id %}">{{ comment.sender.user_name }}</a>&nbsp;&nbsp;{{ comment.add_time|date:"Y-m-d H:m:s" }}</h6>
				{{ comment.content}}
				</div>
	<div class="text-right">
	{% if comment.sender.id ==  login_author.id or login_author.id == author.id %}<a href="{% url remove_comment comment.id %}" class="delete">删除</a>{% endif %}
	{% if login_author.id != comment.sender.id %}<a href="#id_add_comment" class="reply" id="{{comment.sender.user_name}}-{{ comment.id }}">回复</a>{% endif %}
	</div>
</div>
<hr/>
{% endfor %}
</div>
<p></p>
<p>添加评论</p>
<div id="id_add_comment">
<div id="id_error_message"></div>
<form class="form-horizontal" {% if login_author %} action="{% url add_comment blog.id %}" method="post" {% endif %} id="comment-form">{% csrf_token %}
	{% if not login_author %} <fieldset disabled>{% endif %}
	<div class="form-group required">
	<div class="col-sm-12">
		<textarea rows="3" class="form-control comment textarea" name="content" id="id_content"></textarea>
	</div>
	</div>
	<div class="form-group">
	<div class="col-sm-offset-11">
		<input type="submit" value="提交" class="btn btn-default"/>
	</div>
	</div>
	{% if not login_author %}</fieldset>{% endif %}
</form>
</div>
</div>
{% endblock %}
{% block scripts %}
<script src="/static/js/prettify.js"></script>
<script type="text/javascript">
	$(window).load(function(){
		prettyPrint();
	});
	
	$(function(){
		$('#comment-form').submit(function(){
			$('#id_error_message').html('');
			var $strlen = $('#id_content').val().length;
			if($strlen > 280){
				$('#id_error_message').html('不能超过280字！');
				return false;
			}
			$.ajax({
				url: '{% url add_comment blog.id %}',
				type: 'POST',
				data: $(this).serialize(),
				success: function(data){
					$('#comment-area').append(data);
					$('#id_content').val('');
					var $count = parseInt($('#comment_count').html())+1;
					$('#comment_count').html($count+'');
				}
			});
			return false;
		});
		/*
		$('.delete').click(function(evt){
			evt.preventDefault();
			var $commentUrl = $(this).attr('href');
			var $commentID = $(this).attr('id');
			$.get($commentUrl, {}, function(data){
				$('#comment_'+$commentID).hide();
				var $count = parseInt($('#comment_count').html())-1;
				$('#comment_count').html($count+'');
			});
		});
		*/
		$('.reply').click(function(){
			var $commentID = $(this).attr('id');
			var $name = $commentID.split("-")[0];
			$('#id_content').val('@'+$name+':\t');
			$('#id_content').focus();
		});
			
	});
</script>
{% endblock %}


 
	

templates/comment_piece.html
<div id="comment_{{ comment.id }}">
<h6><a href="{% url blog_author comment.sender.id %}">{{ comment.sender.user_name }}</a>&nbsp;&nbsp;{{ comment.add_time|date:"Y-m-d H:m:s" }}</h6>
	{{  comment.content }}
<div class="text-right">
	{% if login_author and comment.sender.id == login_author.id %}<a href="{% url remove_comment comment.id %}" class="delete" id="{{ comment.id }}">删除</a>{% endif %}
	{% if login_author.id != comment.sender.id %}<a href="#reply" class="reply">回复</a>{% endif %}
</div>
</div>
<hr/>

templates/edit_page.html
{% extends "base.html" %}
{% block title %}编辑博客{% endblock %}	
	{% block content %}
	<div id="editpage">
<form name="blog" class="form-horizontal" {% if blog %} action="{% url edit_blog blog.id %}" {% else %} action="{% url add_blog %}" {% endif %} method="post">{% csrf_token %}
	<div class="form-group inline">
		<label for="id_title">标题</label>
		<input type="text" class="form-control" name="title" id="id_title" {% if blog %} value="{{ blog.title }}" {% endif %}>
	</div>
	<div class="form-group required">
	<textarea name="content" id="id_content" style="width:800px; height:400px;">{% if blog %} {{ blog.content }}{% endif %}</textarea>
	</div>
	<div class="form-group required">
		{% if blog %}
		<label class="radio-inline">
			<input type="radio" name="visible_status" id="r1" value="private" {% if not blog.visible %} checked="checked" {% endif %}>自己可见
		</label>
		<label class="radio-inline">
			<input type="radio" name="visible_status" id="public" value="public" {% if blog.visible %} checked="checked"{% endif %}>公开
		</label>
		{% else %}
		<label class="radio-inline">
			<input type="radio" name="visible_status" id="r1" value="private">自己可见
		</label>
		<label class="radio-inline">
			<input type="radio" name="visible_status" id="public" value="public" checked="checked">公开
		</label>
		{% endif %}
	</div>
		<div class="form-group required">
		<label for="category" class="inline">分类</label>
		<select id="category" name="cid" class="form-control">
		{% for category in categories %}
		<option value="{{ category.id }}" {% if blog and blog.category.id == category.id %} selected="selected" {% endif %}>{{ category.category_name }}</option>
		{% endfor %}
		</select>
		</div>
		<div class="form-group required">
		<label>标签</label>
		{% for tag in tags %}
		<label>
		<input type="checkbox" name="tags" value="{{ tag.id }}">{{ tag.tag_name }}
		</label>
		{% endfor %}
		<input type="submit" class="btn btn-success col-sm-offset-11" value="发表"/>
</form>	
	{% endblock %}
	
{% block scripts %}
	<script type="text/javascript">
	$(function(){
		$('#submit-button').click(function(){
		});
	});	
	</script>
	<script charset="utf-8" src="/static/kindeditor/kindeditor.js"></script>
	<script charset="utf-8" src="/static/kindeditor/lang/zh_CN.js"></script>
	<script>
		KindEditor.ready(function(K){
			window.editor = K.create("#id_content", {
				cssData: 'body {font-size: 16px; }', 
				uploadJson: '{% url upload_images %}',
				allowFileManager: true, 
				afterCreate: function(){
					var self = this;
					K.ctrl(document, 13, function(){
						self.sync();
						K('form[name=blog]')[0].submit();
					})
					k.ctrl(self.edit.doc, 13, function(){
						self.sync();
						K('form[name=blog]')[0].submit();
					});
				}
			});
		});
	</script>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="easy-reading with django"/>
<meta name="author" content="Vagrant Wong">
<link rel = "stylesheet" href="/static/css/base.css">
<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="/static/css/base.css">
<link rel="shortcut icon" href="http://miscrocell-miscrocell.stor.sinaapp.com/miscrocell.ico">
<style type="text/css">
      body{background-image: url(/static/images/background-1.jpg); }
      .container{
		background-color: #FFF;
		width: 600px;
	}
</style>
<title>登录</title>
</head>
<body>
<div id="wrap">
<div class="container">
<h2 style="text-align:center"><span class="head_name">登录微克</span></h2>
<form class="form-horizontal" action="{% url login %}" method="post" role="form" id="login-form">{% csrf_token %}
	<input type="hidden" name="trytime" value="{{ trytime }}"/>
	<div class="col-sm-offset-2">
	<span id="id_account_error" class="help-inline">{% if account_error %}用户不存在或密码不正确{% endif %}</span>
	</div>
	<div class="form-group required warning">
	<label class="control-label col-sm-2"  for="id_email">邮箱</label>
	<div class="col-sm-8">
	<input type="text" placeholder="请输入注册邮箱" class="form-control" name="email" id="id_email"/>
	</div>
	</div>
	<div class="form-group required warning">
	<label class="control-label col-sm-2" for="id_password">密码</label>
	<div class="col-sm-8">
	<input type="password" placeholder="请输入密码" class="form-control" name="password" id="id_password"/>
	</div>
	</div>
	{% if trytime > 2 %}
	<div class="form-group">
	<label class="control-label col-sm-2" for="id_verify">验证码</label>
	<div class="col-sm-6">
	<input type="text" placeholder="请输入计算结果" class="form-control" name="verify" id="id_verify"/>
	</div>
	<div class="col-sm-2">
	<img src="{% url get_verifycode %}">
	</div>
	</div>
	{% endif %}
	<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
	<input type="submit" value="登录" class="btn btn-info">&nbsp;&nbsp;&nbsp;没有帐号？
	<a href="{% url register %}">注册</a>&nbsp;&nbsp;&nbsp;
	{% if account_error %}
	<a href="#forget-pass-form">忘记密码？</a>
	{% endif %}
	</div>
	</div>
</form>
{% if account_error %}
<form class="form-horizontal" action="{% url forget_password %}" method="post" id="forget-pass-form">{% csrf_token %}
	<div class="form-group required waring">
	<span id="id_email_error" class="help-inline"></span>
		<label class="control-label col-sm-2"  for="id_verify_email">登录邮箱</label>
		<div class="col-sm-8">
			<input type="text" placeholder="请输入登录邮箱" class="form-control" name="email" id="id_verify_email"/>
		</div>
	</div>
	<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<input type="submit" value="发送邮件" class="btn btn-warning"/>
	</div>
	</div>
</form>
{% endif %}
</div>
</div>
	
<div id="footer">
		<p class="text-muted credit text-center"><a href="{% url about %}">关于微克</a>&nbsp;&nbsp;&nbsp;<a href="#">联系我们</a></p>
</div>
</div>
</body>
<script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script type="text/javascript">
	$(function(){
		$('#forget-pass-form').hide();
		$('#login-form :input').blur(function(){
			var $parent = $(this).parent();
			$parent.find(".formtips").remove();
			
			if($(this).is('#id_email')){
				if(this.value == "" ||  /^[\w\-\.]+@[\w\-\.]+(\.\w+)+$/.test(this.value) == false){
					$parent.append('<span class="help-inline">请输入正确邮箱地址</span>');
				}
			}
			
			if($(this).is('#id_password')){
				if(this.value == ""){
					$parent.append('<span class="help-inline">密码不能为空</span>');
				}
			}
		});
		
		$('#login-form').submit(function(){
			$("#login-form :input").trigger('blur');
			var error = $('#login-form .onError').length;
			if( error ){
				return false;
			}
		});
		
		$('a[href="#forget-pass-form"]').click(function(){
			$('#login-form').hide();
			$('.head_name').text('取回密码');
			$('#forget-pass-form').show();
		});

		$('#forget-pass-form').submit(function(){
			var $email = $('#id_verify_email').val();
			if( $email == "" || /^[\w\-\.]+@[\w\-\.]+(\.\w+)+$/.test($email) == false){
				$('#id_verify_email').val('请输入正确的邮箱地址');
				return false;
			}
		
			$.ajax({
				url: '{% url forget_password %}',
				type: 'POST',
				data: $(this).serialize(),
				success: function(data){
					if(data.status == 'success'){
						$('.head_name').text('登录微克');
						$('#forget-pass-form').hide();
						$('#login-form').show();
						$('#id_account_error').text('');
						alert('已发送邮件到您的登录邮箱，请查收！');
					}else{
						$('#id_verify_email').val('');
						$('#id_verify_email').val('邮箱不存在');
					}			
				}
			});
			return false;
		});
					
	});
</script>
</html>